//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackboard_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        public int School_ID { get; set; }
        public string first_Name { get; set; }
        public string last_Name { get; set; }
        public Nullable<int> Course_Taken { get; set; }
        public string Class_1_Midterm { get; set; }
        public string Class_2_Midterm { get; set; }
        public string Class_3_Midterm { get; set; }
        public string Class_4_Midterm { get; set; }
        public string Class_1_Finals { get; set; }
        public string Class_2_Finals { get; set; }
        public string Class_3_Finals { get; set; }
        public string Class_4_Finals { get; set; }
        public string GPA { get; set; }
        public string username { get; set; }
    }
}
